### ISSUE TITLE
Invalid version of library in npm

### ISSUE THREAD

**Issue by dev-tim** [elmariachi111/passport-eyeem#4]
Hi!  There is invalid version of this library in npm repo.
Some URLs points to, probably, old version of the API.

If you get passport-eyeem library via `npm install passport-eyeem` you will figure out that library doesn't work because:
- tokenURL points to `http://www.eyeem.com/API/v2/oauth/token` instead of `https://api.eyeem.com/v2/oauth/token`
- API host for users also points to the wrong endpoint -  `http://www.eyeem.com/api/v2/users/me` instead of `https://api.eyeem.com/v2/users/me`

To solve this just update package.json and add a tag with version 0.1.2 via

```
git tag 0.1.2
git push --tags
```

**Comment by cainvommars** [comment]
@elmariachi111 would also like to see this fixed, thanks!

**Comment by elmariachi111** [comment]
Sorry guys, I didn't dev-tim's point in April - too much work. Published release 0.1.2 including https routes (the http ones must be from their very first hackathon back in 2012)

Cheers

**Comment by ptrwllrt** [comment]
@elmariachi111 Thanks! We're working in frontend at eyeem and use this project sometimes. :)
